issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't ignore some of the issues that golangci-lint considers okay.
  exclude-use-default: false

  exclude-rules:
    # Don't warn on unused parameters.
    # Parameter names are useful; replacing them with '_' is undesirable.
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

output:
  # Make output more digestible with quickfix in vim.
  sort-results: true
  print-issued-lines: false

linters:
  enable:
    - gofumpt
    - nolintlint
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
  govet:
    enable:
      - nilness
      - reflectvaluecompare
      - sortslice
      - unusedwrite
