version: "2"

issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - nolintlint
    - revive
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

      # TODO: https://github.com/abhinav/doc2go/issues/259
      - linters:
          - staticcheck
        text: 'ast.\S+ has been deprecated'

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
