name: CI

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ '*' ]

env:
  GO_VERSION: 1.20.x

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out repository
    - uses: actions/setup-go@v4
      name: Set up Go
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    - uses: golangci/golangci-lint-action@v3
      name: Install golangci-lint
      with:
        version: latest
        args: --version
    - run: make lint
      name: Lint


  test:
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os}})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Build
      run: make build
      shell: bash

    - name: Test
      run: make cover
      env:
        TEST_FLAGS: '-v -race'
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v3
