name: CI

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ '*' ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out repository
    - uses: actions/setup-go@v5
      name: Set up Go
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v6
      name: Install golangci-lint
      with:
        version: latest
        args: --help
    - run: make lint
      name: Lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os}})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Test
      run: make cover
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.out

  test-integration:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    # Node is needed to download pagefind.
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: integration/package-lock.json

    - name: Test
      run: make cover-integration
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.integration.out
