name: CI

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ '*' ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out repository
    - name: Set up mise
      uses: jdx/mise-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        cache_key_prefix: mise-v0-stable
    - run: mise run lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os}})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up mise
      uses: jdx/mise-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        cache_key_prefix: mise-v0-stable

    - name: Test
      run: mise run cover:unit
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.out

  test-integration:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
    - uses: actions/checkout@v4
    - name: Set up mise
      uses: jdx/mise-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        cache_key_prefix: mise-v0-stable

    - name: Test
      run: mise run cover:integration
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.integration.out
