name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true

    - name: Lint
      run: make lint

    - name: Build
      run: make build

    - name: Test
      run: make cover
      env:
        TEST_FLAGS: '-v -race'

    # TODO: Enable after public
    # - name: Upload coverage
    #   uses: codecov/codecov-action@v3
